export const products = [
  {
    id: 1,
    name: "Product A",
    businessLocation: "Location 1",
    unitPurchasePrice: 10.5,
    sellingPrice: 15.99,
    currentStock: 100,
    productType: "Type 1",
    category: "Category A",
    brand: "Brand X",
    tax: "GST",
    sku: "SKU123",
    image: "https://placehold.co/32x32",
  },
  {
    id: 2,
    name: "Product B",
    businessLocation: "Location 2",
    unitPurchasePrice: 8.75,
    sellingPrice: 12.49,
    currentStock: 75,
    productType: "Type 2",
    category: "Category B",
    brand: "Brand Y",
    tax: "VAT",
    sku: "SKU456",
    image: "https://placehold.co/32x32",
  },
  {
    id: 3,
    name: "Product C",
    businessLocation: "Location 1",
    unitPurchasePrice: 12.99,
    sellingPrice: 19.99,
    currentStock: 50,
    productType: "Type 1",
    category: "Category A",
    brand: "Brand Z",
    tax: "None",
    sku: "SKU789",
    image: "https://placehold.co/32x32",
  },
  {
    id: 4,
    name: "Product D",
    businessLocation: "Location 3",
    unitPurchasePrice: 15.25,
    sellingPrice: 22.5,
    currentStock: 120,
    productType: "Type 3",
    category: "Category C",
    brand: "Brand X",
    tax: "GST",
    sku: "SKU4567",
    image: "https://placehold.co/32x32",
  },
  {
    id: 5,
    name: "Product E",
    businessLocation: "Location 2",
    unitPurchasePrice: 9.99,
    sellingPrice: 14.99,
    currentStock: 90,
    productType: "Type 1",
    category: "Category B",
    brand: "Brand Y",
    tax: "VAT",
    sku: "SKU890",
    image: "https://placehold.co/32x32",
  },
  {
    id: 6,
    name: "Product F",
    businessLocation: "Location 1",
    unitPurchasePrice: 11.5,
    sellingPrice: 17.99,
    currentStock: 65,
    productType: "Type 2",
    category: "Category A",
    brand: "Brand Z",
    tax: "None",
    sku: "SKU1234",
    image: "https://placehold.co/32x32",
  },
  {
    id: 7,
    name: "Product G",
    businessLocation: "Location 3",
    unitPurchasePrice: 18.75,
    sellingPrice: 27.49,
    currentStock: 110,
    productType: "Type 3",
    category: "Category C",
    brand: "Brand X",
    tax: "GST",
    sku: "SKU5678",
    image: "https://placehold.co/32x32",
  },
  {
    id: 8,
    name: "Product H",
    businessLocation: "Location 2",
    unitPurchasePrice: 14.99,
    sellingPrice: 21.99,
    currentStock: 80,
    productType: "Type 1",
    category: "Category B",
    brand: "Brand Y",
    tax: "VAT",
    sku: "SKU2345",
    image: "https://placehold.co/32x32",
  },
  {
    id: 9,
    name: "Product I",
    businessLocation: "Location 1",
    unitPurchasePrice: 13.25,
    sellingPrice: 19.5,
    currentStock: 70,
    productType: "Type 2",
    category: "Category A",
    brand: "Brand Z",
    tax: "None",
    sku: "SKU6789",
    image: "https://placehold.co/32x32",
  },
  {
    id: 10,
    name: "Product J",
    businessLocation: "Location 3",
    unitPurchasePrice: 16.99,
    sellingPrice: 24.99,
    currentStock: 100,
    productType: "Type 3",
    category: "Category C",
    brand: "Brand X",
    tax: "GST",
    sku: "SKU3456",
    image: "https://placehold.co/32x32",
  },
  {
    id: 11,
    name: "Product K",
    businessLocation: "Location 2",
    unitPurchasePrice: 12.5,
    sellingPrice: 18.99,
    currentStock: 85,
    productType: "Type 1",
    category: "Category B",
    brand: "Brand Y",
    tax: "VAT",
    sku: "SKU7890",
    image: "https://placehold.co/32x32",
  },
  {
    id: 12,
    name: "Product L",
    businessLocation: "Location 1",
    unitPurchasePrice: 19.99,
    sellingPrice: 29.99,
    currentStock: 60,
    productType: "Type 2",
    category: "Category A",
    brand: "Brand Z",
    tax: "None",
    sku: "SKU12345",
    image: "https://placehold.co/32x32",
  },
  {
    id: 13,
    name: "Product M",
    businessLocation: "Location 3",
    unitPurchasePrice: 17.25,
    sellingPrice: 25.5,
    currentStock: 95,
    productType: "Type 3",
    category: "Category C",
    brand: "Brand X",
    tax: "GST",
    sku: "SKU67890",
    image: "https://placehold.co/32x32",
  },
  {
    id: 14,
    name: "Product N",
    businessLocation: "Location 2",
    unitPurchasePrice: 10.99,
    sellingPrice: 16.99,
    currentStock: 75,
    productType: "Type 1",
    category: "Category B",
    brand: "Brand Y",
    tax: "VAT",
    sku: "SKU23456",
    image: "https://placehold.co/32x32",
  },
];

export const categories = [
  {
    id: 1,
    name: "Category A",
    value: "category-a",
  },
  {
    id: 2,
    name: "Category B",
    value: "category-b",
  },
  {
    id: 3,
    name: "Category C",
    value: "category-c",
  },
  {
    id: 4,
    name: "Category D",
    value: "category-d",
  },
  {
    id: 5,
    name: "Category E",
    value: "category-e",
  },
  {
    id: 6,
    name: "Category F",
    value: "category-f",
  },
  {
    id: 7,
    name: "Category G",
    value: "category-g",
  },
  {
    id: 8,
    name: "Category H",
    value: "category-h",
  },
  {
    id: 9,
    name: "Category I",
    value: "category-i",
  },
  {
    id: 10,
    name: "Category J",
    value: "category-j",
  },
  {
    id: 11,
    name: "Category K",
    value: "category-k",
  },
  {
    id: 12,
    name: "Category L",
    value: "category-l",
  },
  {
    id: 13,
    name: "Category M",
    value: "category-m",
  },
  {
    id: 14,
    name: "Category N",
    value: "category-n",
  },
];

export const brands = [
  {
    id: 1,
    name: "Brand A",
    value: "brand-a",
  },
  {
    id: 2,
    name: "Brand B",
    value: "brand-b",
  },
  {
    id: 3,
    name: "Brand C",
    value: "brand-c",
  },
  {
    id: 4,
    name: "Brand D",
    value: "brand-d",
  },
  {
    id: 5,
    name: "Brand E",
    value: "brand-e",
  },
  {
    id: 6,
    name: "Brand F",
    value: "brand-f",
  },
  {
    id: 7,
    name: "Brand G",
    value: "brand-g",
  },
  {
    id: 8,
    name: "Brand H",
    value: "brand-h",
  },
  {
    id: 9,
    name: "Brand I",
    value: "brand-i",
  },
  {
    id: 10,
    name: "Brand J",
    value: "brand-j",
  },
  {
    id: 11,
    name: "Brand K",
    value: "brand-k",
  },
  {
    id: 12,
    name: "Brand L",
    value: "brand-l",
  },
  {
    id: 13,
    name: "Brand M",
    value: "brand-m",
  },
  {
    id: 14,
    name: "Brand N",
    value: "brand-n",
  },
];

export const businessLocations = [
  {
    id: 1,
    name: "Location 1",
    value: "location-1",
  },
  {
    id: 2,
    name: "Location 2",
    value: "location-2",
  },
  {
    id: 3,
    name: "Location 3",
    value: "location-3",
  },
  {
    id: 4,
    name: "Location 4",
    value: "location-4",
  },
  {
    id: 5,
    name: "Location 5",
    value: "location-5",
  },
  {
    id: 6,
    name: "Location 6",
    value: "location-6",
  },
  {
    id: 7,
    name: "Location 7",
    value: "location-7",
  },
  {
    id: 8,
    name: "Location 8",
    value: "location-8",
  },
  {
    id: 9,
    name: "Location 9",
    value: "location-9",
  },
  {
    id: 10,
    name: "Location 10",
    value: "location-10",
  },
  {
    id: 11,
    name: "Location 11",
    value: "location-11",
  },
  {
    id: 12,
    name: "Location 12",
    value: "location-12",
  },
  {
    id: 13,
    name: "Location 13",
    value: "location-13",
  },
  {
    id: 14,
    name: "Location 14",
    value: "location-14",
  },
];

export const units = [
  {
    id: 1,
    name: "Pieces",
    value: "pieces",
  },
  {
    id: 2,
    name: "Kilograms",
    value: "kilograms",
  },
  {
    id: 3,
    name: "Liters",
    value: "liters",
  },
  {
    id: 4,
    name: "Meters",
    value: "meters",
  },
  {
    id: 5,
    name: "Gallons",
    value: "gallons",
  },
  {
    id: 6,
    name: "Pounds",
    value: "pounds",
  },
  {
    id: 7,
    name: "Dozens",
    value: "dozens",
  },
  {
    id: 8,
    name: "Boxes",
    value: "boxes",
  },
  {
    id: 9,
    name: "Packs",
    value: "packs",
  },
  {
    id: 10,
    name: "Bottles",
    value: "bottles",
  },
  {
    id: 11,
    name: "Cans",
    value: "cans",
  },
  {
    id: 12,
    name: "Bags",
    value: "bags",
  },
  {
    id: 13,
    name: "Rolls",
    value: "rolls",
  },
  {
    id: 14,
    name: "Sets",
    value: "sets",
  },
];
